// AUTHENTICATION
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

// MESSAGE
export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

// SUPPLIERS
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS'
export const ADD_SUPPLIER_FAIL = 'ADD_SUPPLIER_FAIL'
export const FETCH_SUPPLIERS_SUCCESS = 'FETCH_SUPPLIERS_SUCCESS'
export const FETCH_SUPPLIERS_FAIL = 'FETCH_SUPPLIERS_FAIL'
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS'
export const DELETE_SUPPLIER_FAIL = 'DELETE_SUPPLIER_FAIL'

// INVOICES
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS'
export const ADD_INVOICE_FAIL = 'ADD_INVOICE_FAIL'
export const FETCH_INVOICES_SUCCESS = 'FETCH_SINVOICE_SUCCESS'
export const FETCH_INVOICES_FAIL = 'FETCH_SINVOICE_FAIL'
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS'
export const DELETE_INVOICE_FAIL = 'DELETE_INVOICE_FAIL'

// EMPLOYEES
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS'
export const FETCH_EMPLOYEES_FAIL = 'FETCH_EMPLOYEES_FAIL'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

// CATEGORIES
export const ADD_CATEGORIES_SUCCESS = 'ADD_CATEGORIES_SUCCESS'
export const ADD_CATEGORIES_FAIL = 'ADD_CATEGORIES_FAIL'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL'
export const DELETE_CATEGORIES_SUCCESS = 'DELETE_CATEGORIES_SUCCESS'
export const DELETE_CATEGORIES_FAIL = 'DELETE_CATEGORIES_FAIL'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL'
